sudo: required

language: generic

services:
  - docker

before_install:
  - source version.sh
  - echo $VERSION
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f latest/Dockerfile -t bjreppen/node-red-zwave .
  - docker tag bjreppen/node-red-zwave bjreppen/node-red-zwave:$VERSION

script:
  - docker run -d bjreppen/node-red-zwave:latest
  - docker ps | grep latest
  - docker run -d bjreppen/node-red-zwave:v8
  - docker ps | grep v8

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push bjreppen/node-red-zwave;
    fi
